"""Added roles

Revision ID: 4b49364ae844
Revises: 02358a4946e9
Create Date: 2025-08-25 04:09:16.333208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.auth.models import Role
from src.auth.schemas import RoleEnum

# revision identifiers, used by Alembic.
revision: str = '4b49364ae844'
down_revision: Union[str, Sequence[str], None] = '02358a4946e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###

    op.bulk_insert(
        Role.__table__,
        [
            {"id": 1, "name": RoleEnum.ADMIN.value},
            {"id": 2, "name": RoleEnum.USER.value},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
